Only fund when faucet balance drops below 10 000 000 sats
get10101/10101 pull request #1003
Opened 2023-07-25 13:00 UTC by Restioson

This speeds up development a little bit. The balance is retrieved by `curl`ing the channel balance.

I left this out of  the `fund-regtest` recipe since it seems to be a manually invoked recipe and not an automated prerequiste, hence it is not really needed.

2023-07-25 13:18 UTC, bonomat requested changes
Not ideal this change: sometimes we will need to fund an already funded node again.

2023-07-25 13:20 UTC, Restioson commented
> Not ideal this change: sometimes we will need to fund an already funded node again.

Maybe a new `force-fund` command for that? Or, a new `autofund` command and use that for the prerequisite in `all` etc.

For context, the problem I am trying to solve is the fund process being run *every time* I run `just all` to start the app for debugging

2023-07-25 13:24 UTC, bonomat commented
> > Not ideal this change: sometimes we will need to fund an already funded node again.
> 
> Maybe a new `force-fund` command for that? Or, a new `autofund` command and use that for the prerequisite in `all` etc.
> 
> For context, the problem I am trying to solve is the fund process being run _every time_ I run `just all` to start the app for debugging

I never use this command 🙈 I like to keep an eye on what things happen and call each step separately. 

I'm fine with a different function or an extra arg I can pass in to _force_ funding again.

2023-07-25 13:41 UTC, Restioson commented
Fair enough! Do you have any preference as to a new command or arg?

2023-07-25 13:44 UTC, bonomat commented
> Fair enough! Do you have any preference as to a new command or arg?

Eitherway is fine with me :)

2023-07-25 13:56 UTC, Restioson commented
Added arguments -f & --force

2023-07-28 08:18 UTC, bonomat approved these changes
lgtm

2023-07-28 08:39 UTC, merged