Refresh on-chain txs in background
get10101/10101 pull request #1294
Opened 2023-09-13 14:51 UTC by Restioson

Fixes #1288

2023-09-14 12:40 UTC, holzeis requested changes
Lets spawn a task on the rust side instead of blocking a frb thread (we have only 4) every 30 seconds for about 5-7 seconds.

2023-09-14 12:42 UTC, holzeis commented
Note, if we'd also remove the initial sync on startup this should also fix https://github.com/get10101/10101/issues/1258

2023-09-15 07:16 UTC, bonomat commented on mobile/lib/features/wallet/wallet_change_notifier.dart
> +      await refreshWalletInfo();
I'm not sure if it does, but if `refreshWalletInfo` triggers an on-chain sync, than this would be too often.

2023-09-15 12:29 UTC, Restioson commented
> Lets spawn a task on the rust side instead of blocking a frb thread (we have only 4) every 30 seconds for about 5-7 seconds.

Ah, I didn't realised it blocked a FRB thread, can fix that too

2023-09-19 15:27 UTC, luckysori reviewed
I think this is unnecessary, as we already have a periodic task managed by the `ln_dlc_node::Node`. See https://github.com/get10101/10101/issues/1288#issuecomment-1725887321.

2023-09-20 17:50 UTC, holzeis commented
Can we close that after also #1332 has been merged?

2023-09-26 08:14 UTC, closed without merging

2023-09-26 08:14 UTC, Restioson commented
Indeed it can be closed as @luckysori mentioned this isn't needed