fix: Improve faucet invoice payment error handling
get10101/10101 pull request #631
Opened 2023-05-10 21:05 UTC by klochowicz

Faucet payment can fail in more ways than just faucet being unreachable.
Parse the response for `payment_error` phrase and count it as an error.
For simplicity, print the whole response in such cases.

2023-05-10 21:52 UTC, luckysori approved these changes

2023-05-11 07:33 UTC, holzeis approved these changes

2023-05-11 07:44 UTC, holzeis requested changes
I just checked! The following is an example response of a successful payment. It  contains the `payment_error` property, even if no error happened.

```
{"payment_error":"", "payment_preimage":"QsMT843FTzY4n0klfsU5D/JQSyFdeUOdqrS+/pSd/M0=", "payment_route":{"total_time_lock":2099, "total_fees":"251", "total_amt":"50251", "hops":[{"chan_id":"2219913976545281", "chan_capacity":"10000000", "amt_to_forward":"50000", "fee":"251", "expiry":2057, "amt_to_forward_msat":"50000000", "fee_msat":"251000", "pub_key":"03507b924dae6595cfb78492489978127c5f1e3877848564de2015cd6d41375802", "tlv_payload":true, "mpp_record":null, "amp_record":null, "custom_records":{}, "metadata":""}, {"chan_id":"1099538169860", "chan_capacity":"50000", "amt_to_forward":"50000", "fee":"0", "expiry":2057, "amt_to_forward_msat":"50000000", "fee_msat":"0", "pub_key":"0264210a5c3d478bbe4145bd514385868e3462412ebbcca2a2cf0aa802d26ee165", "tlv_payload":true, "mpp_record":{"payment_addr":"q+xfLhy4CbmlVmaH7iR84QaTqE7RNvNt4KZMzNiH2b4=", "total_amt_msat":"50000000"}, "amp_record":null, "custom_records":{}, "metadata":""}], "total_fees_msat":"251000", "total_amt_msat":"50251000"}, "payment_hash":"Di0jkqWkyUz4hOArLI9xYMMmoLQ/I/6SPnsHzmxHxlw="}
```

If I am not mistaken this change would now lead to the Exception being thrown all the time?

2023-05-11 14:01 UTC, klochowicz commented
> I just checked! The following is an example response of a successful payment. It contains the `payment_error` property, even if no error happened.
> 
> ```
> {"payment_error":"", "payment_preimage":"QsMT843FTzY4n0klfsU5D/JQSyFdeUOdqrS+/pSd/M0=", "payment_route":{"total_time_lock":2099, "total_fees":"251", "total_amt":"50251", "hops":[{"chan_id":"2219913976545281", "chan_capacity":"10000000", "amt_to_forward":"50000", "fee":"251", "expiry":2057, "amt_to_forward_msat":"50000000", "fee_msat":"251000", "pub_key":"03507b924dae6595cfb78492489978127c5f1e3877848564de2015cd6d41375802", "tlv_payload":true, "mpp_record":null, "amp_record":null, "custom_records":{}, "metadata":""}, {"chan_id":"1099538169860", "chan_capacity":"50000", "amt_to_forward":"50000", "fee":"0", "expiry":2057, "amt_to_forward_msat":"50000000", "fee_msat":"0", "pub_key":"0264210a5c3d478bbe4145bd514385868e3462412ebbcca2a2cf0aa802d26ee165", "tlv_payload":true, "mpp_record":{"payment_addr":"q+xfLhy4CbmlVmaH7iR84QaTqE7RNvNt4KZMzNiH2b4=", "total_amt_msat":"50000000"}, "amp_record":null, "custom_records":{}, "metadata":""}], "total_fees_msat":"251000", "total_amt_msat":"50251000"}, "payment_hash":"Di0jkqWkyUz4hOArLI9xYMMmoLQ/I/6SPnsHzmxHxlw="}
> ```
> 
> If I am not mistaken this change would now lead to the Exception being thrown all the time?

indeed, it would make the snackbar appear in this case too. it's not the end of the world, as the whole thing would still work 🤪
I have to stop somewhere on the non-essential things, as making this even nicer is not high on my priority list.

I would still merge this in as the snackbar is always shown. :)

2023-05-11 17:24 UTC, holzeis approved these changes

2023-05-11 19:18 UTC, klochowicz commented
bors r+

2023-05-11 19:24 UTC, merged